### ISSUE TITLE
adding js files / missing space between attributes

### ISSUE THREAD

**Issue by jlnschfr** [miyagi-dev/miyagi#209]
**Describe the bug**
When a js file is added with the following configuration, there are missing spaces between attributes

**To Reproduce**
1. add js file with this configuration

```
    {
      src: "assets/js/index.js",
      type: "module",
      defer: true,
    },
```

2. this script gets added
```
<script src="assets/js/index.js" type="module"defer></script>
```

**Expected behavior**
There should be a space between every attribute.
```
<script src="build/assets/js/index.js" type="module" defer></script>
```

**Comment by mgrsskls** [comment]
Hey, I can fix this at some point, but defer and type=module are mutually exclusive as modules are always loaded deferred: https://javascript.info/modules-intro#module-scripts-are-deferred

**Comment by mgrsskls** [comment]
Fixed in current release!
