### ISSUE TITLE
Unescaped components ignore/exclude regexes

### ISSUE THREAD

**Issue by mvsde** [miyagi-dev/miyagi#216]
**Describe the bug**
miyagi can’t create the directory tree structure when the project folder’s path contains strings that are matched by the ignore/exclude regexes for `directory-tree`.

**To Reproduce**
1. Create a miyagi project in a folder whose path contains `git` (e.g. `github` or `gitlab`).
2. Start miyagi either with `miyagi start` or `miyagi build`.
3. See error message:

```
Error: The provided components directory 'whatever' does not seem to exist. You can specify this in your config file (key: 'components.folder', type: String) or as a cli argument (--components.folder=<String>).
```

**Expected behavior**
The projects works as usual since the components folder exists.

**Additional context**
The following code…

https://github.com/miyagi-dev/miyagi/blob/8098a22a3f738365bbf64a5e8f78802be4f28876/packages/core/lib/state/source-tree.js#L22

…produces regexes that look like this:

```js
[
  /node_modules/,
  /.git/,
  /package.json/,
  /package-lock.json/,
  /.miyagi.js/,
  /.miyagi.json/
]
```

Note: The `.` in the file names isn’t escaped which creates overly broad exclude patterns.

**Comment by mgrsskls** [comment]
Finally fixed in https://github.com/miyagi-dev/miyagi/releases/tag/core%2Fv3.3.6. Thanks, @mvsde!
