### ISSUE TITLE
Parent components should indicate if child components have invalid mock data.

### ISSUE THREAD

**Issue by riidom** [miyagi-dev/miyagi#295]
**Is your feature request related to a problem? Please describe.**
Problem is, when there are subcomponents layers deep, you have to open them all to see if any of them has invalid mock data.

**Describe the solution you'd like**
It would be nice if the parent component displays whether the child components have invalid mock data and gives a hint about that (preferably with the name of the affected subcomponent).

**Describe alternatives you've considered**
Maybe it is simpler done when this process can be started manually via a button?

**Additional context**
-

**Comment by mgrsskls** [comment]
I think that is not really doable, at least not without very high effort. The data gets passed as a whole to the 3rd party validator.

I will keep the issue open and see at some point if there is anything I can do about that.

**Comment by mgrsskls** [comment]
Double checked it and yes, this is not possible unfortunately. However, you can always run `miyagi lint` which validates the whole project, so you would definitely see those errors there.
