### ISSUE TITLE
CLI status messages appear to be off by one month

### ISSUE THREAD

**Issue by dokumori** [miyagi-dev/miyagi#296]
**Describe the bug**
When executing Miyagi commands via cli, the dates that accompany status messages appear to be off by one month

**To Reproduce**
1. run `yarn start:cl`
2. each status message displays the date, but it is off by one month

**Expected behavior**
The status message displays the correct date

**Screenshots**
<img width="787" alt="Screenshot 2023-08-21 at 10 38 16" src="https://github.com/miyagi-dev/miyagi/assets/383205/6561cc6f-54d2-4495-8c7a-d41820224af7">

**Comment by mgrsskls** [comment]
Thank you! Fixed in https://github.com/miyagi-dev/miyagi/releases/tag/core%2Fv3.4.8.
