### ISSUE TITLE
`dist` folder missing in 3.4.8 npm release

### ISSUE THREAD

**Issue by mvsde** [miyagi-dev/miyagi#298]
**Describe the bug**
The `dist` folder is missing in the 3.4.8 release on npm.

**To Reproduce**
1. Go to the [npm code page for miyagi](https://www.npmjs.com/package/@miyagi/core?activeTab=code)
2. There is no `dist` folder

**Expected behavior**
The release includes the `dist` folder.

**Comment by mgrsskls** [comment]
Thanks… 🙈 Fixed in https://github.com/miyagi-dev/miyagi/releases/tag/core%2Fv3.4.9.
