### ISSUE TITLE
Client / Developer mode

### ISSUE THREAD

**Issue by mgrsskls** [miyagi-dev/miyagi#300]
- _miyagi_ should have two modes: client mode and developer mode
- developer mode is the current state, showing schema, mocks etc.
- client mode should hide developer related information
- Builds should support both modes
- developer mode should probably be the default as that would be used more often
- How would define the mode? env var? cli param?
- Can this be toggled in the UI? If so, do we set a cookie / use local storage?
- Better name for client mode?

**Comment by schalkneethling** [comment]
My vote would be for a UI toggle persisted using localStoratge. 

What about presentation mode?

**Comment by mgrsskls** [comment]
> My vote would be for a UI toggle persisted using localStoratge.

Thank you for the confirmation, that were exactly my thoughts today or yesterday :)

> What about presentation mode?

That sounds good :)
