### ISSUE TITLE
More information about automated styleguides returns 404

### ISSUE THREAD

**Issue by schalkneethling** [miyagi-dev/miyagi#360]
**Describe the bug**
The link to "[More information about automated styleguides](https://docs.miyagi.dev/automated-styleguide)." on https://docs.miyagi.dev/configuration/options/ returns a 404.

**To Reproduce**

1. Go to https://docs.miyagi.dev/configuration/options/
2. Click on More information about automated styleguides
3. Error 404

**Expected behavior**
It should return a page with more information about automated styleguides.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Arc (Chromium)
- Version 129

**Comment by mgrsskls** [comment]
Thank you, @schalkneethling! Fixed in v4.
